baseurl = "https://ramnottath.netlify.com/"
title = "Discovering The Goodness In Data"
theme = "hugo-swift-theme"
author = "Ramkumar Nottath"
canonifyurls = true
paginate = 2
[params]
  staticman = false # turn this to true to enable staticman. See theme README